/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconAntDesignPoweroffOutlined: typeof import('~icons/ant-design/poweroff-outlined.jsx')['default']
  const IconAntDesignSearchOutlined: typeof import('~icons/ant-design/search-outlined.jsx')['default']
}
