import { createGlobalThemeContract } from "@vanilla-extract/css"

export const prefix = "x"
export const token = createGlobalThemeContract({
    fontFamily: `${prefix}-font-family`,
    fontFamilyCode: `${prefix}-font-family-code`,
    linkDecoration: `${prefix}-link-decoration`,
    fontWeightStrong: `${prefix}-font-weight-strong`,
    height: {
        small: `${prefix}-control-height-sm`,
        middle: `${prefix}-control-height`,
        large: `${prefix}-control-height-lg`,
    },
    size: {
        xxs: `${prefix}-size-xxs`,
        xs: `${prefix}-size-xs`,
        sm: `${prefix}-size-sm`,
        default: `${prefix}-size`,
        md: `${prefix}-size-md`,
        lg: `${prefix}-size-lg`,
        xl: `${prefix}-size-xl`,
        xxl: `${prefix}-size-xxl`,
    },
    borderRadius: {
        sm: `${prefix}-border-radius-sm`,
        default: `${prefix}-border-radius`,
        lg: `${prefix}-border-radius-lg`,
    },
    line: {
        width: `${prefix}-lin-width`,
        widthBold: `${prefix}-line-width-bold`,
        type: `${prefix}-line-type`,
    },
    motion: {
        fast: `${prefix}-motion-fast`,
        mid: `${prefix}-motion-mid`,
        slow: `${prefix}-motion-slow`,
        unit: `${prefix}-motion-unit`,
        base: `${prefix}-motion-base`,
        easeOutCirc: `${prefix}-motion-ease-out-circ`,
        easeInOutCirc: `${prefix}-motion-ease-in-out-circ`,
        easeOut: `${prefix}-motion-ease-out`,
        easeInOut: `${prefix}-motion-ease-in-out`,
        easeOutBack: `${prefix}-motion-ease-out-back`,
        easeInBack: `${prefix}-motion-ease-in-back`,
        easeInQuint: `${prefix}-motion-ease-in-quint`,
        easeOutQuint: `${prefix}-motion-ease-in-quint`,
    },
    colors: {
        white: `${prefix}-color-white`,
        text: {
            default: `${prefix}-color-text`,
            secondary: `${prefix}-color-secondary`,
            tertiary: `${prefix}-color-tertiary`,
            quaternary: `${prefix}-color-quaternary`,
            description: `${prefix}-color-text-description`,
        },
        link: {
            default: `${prefix}-color-link`,
            hover: `${prefix}-color-link-hover`,
            active: `${prefix}-color-link-active`,
        },
        fill: {
            default: `${prefix}-color-fill-text`,
            secondary: `${prefix}-color-fill-secondary`,
            tertiary: `${prefix}-color-fill-tertiary`,
            quaternary: `${prefix}-color-fill-quaternary`,
        },
        bg: {
            solid: {
                default: `${prefix}-color-bg-solid`,
                hover: `${prefix}-color-bg-solid-hover`,
                active: `${prefix}-color-bg-solid-active`,
            },
            layout: `${prefix}-color-bg-layout`,
            container: `${prefix}-color-bg-container`,
            elevated: `${prefix}-color-bg-elevated`,
            spotlight: `${prefix}-color-bg-spotlight`,
            blur: `${prefix}-color-bg-blur`,
        },
        border: {
            default: `${prefix}-color-bg-border`,
            secondary: `${prefix}-color-bg-border-secondary`,
        },
        primary: {
            default: `${prefix}-color-primary`,
            hover: `${prefix}-color-primary-hover`,
            active: `${prefix}-color-primary-active`,
            bg: `${prefix}-color-primary-bg`,
            bgHover: `${prefix}-color-primary-bg-hover`,
            border: `${prefix}-color-primary-border`,
            borderHover: `${prefix}-color-primary-border-hover`,
            text: `${prefix}-color-primary-text`,
            textHover: `${prefix}-color-primary-text-hover`,
            textActive: `${prefix}-color-primary-text-active`,
            outline: `${prefix}-color-primary-outline`,
        },
        success: {
            default: `${prefix}-color-success`,
            hover: `${prefix}-color-success-hover`,
            active: `${prefix}-color-success-active`,
            bg: `${prefix}-color-success-bg`,
            bgHover: `${prefix}-color-success-bg-hover`,
            border: `${prefix}-color-success-border`,
            borderHover: `${prefix}-color-success-border-hover`,
            text: `${prefix}-color-success-text`,
            textHover: `${prefix}-color-success-text-hover`,
            textActive: `${prefix}-color-success-text-active`,
            outline: `${prefix}-color-success-outline`,
        },
        warning: {
            default: `${prefix}-color-warning`,
            hover: `${prefix}-color-warning-hover`,
            active: `${prefix}-color-warning-active`,
            bg: `${prefix}-color-warning-bg`,
            bgHover: `${prefix}-color-warning-bg-hover`,
            border: `${prefix}-color-warning-border`,
            borderHover: `${prefix}-color-warning-border-hover`,
            text: `${prefix}-color-warning-text`,
            textHover: `${prefix}-color-warning-text-hover`,
            textActive: `${prefix}-color-warning-text-active`,
            outline: `${prefix}-color-warning-outline`,
        },
        info: {
            default: `${prefix}-color-info`,
            hover: `${prefix}-color-info-hover`,
            active: `${prefix}-color-info-active`,
            bg: `${prefix}-color-info-bg`,
            bgHover: `${prefix}-color-info-bg-hover`,
            border: `${prefix}-color-info-border`,
            borderHover: `${prefix}-color-info-border-hover`,
            text: `${prefix}-color-info-text`,
            textHover: `${prefix}-color-info-text-hover`,
            textActive: `${prefix}-color-info-text-active`,
            outline: `${prefix}-color-info-outline`,
        },
        danger: {
            default: `${prefix}-color-danger`,
            hover: `${prefix}-color-danger-hover`,
            active: `${prefix}-color-danger-active`,
            bg: `${prefix}-color-danger-bg`,
            bgActive: `${prefix}-color-danger-bg-active`,
            bgHover: `${prefix}-color-danger-bg-hover`,
            bgFilledHover: `${prefix}-color-danger-bg-filled-hover`,
            border: `${prefix}-color-danger-border`,
            borderHover: `${prefix}-color-danger-border-hover`,
            text: `${prefix}-color-danger-text`,
            textHover: `${prefix}-color-danger-text-hover`,
            textActive: `${prefix}-color-danger-text-active`,
            outline: `${prefix}-color-danger-outline`,
        },
        split: `${prefix}-color-split`,
    },
    fontSize: {
        sm: `${prefix}-font-size-sm`,
        default: `${prefix}-font-size`,
        lg: `${prefix}-font-size-lg`,
        xl: `${prefix}-font-size-xl`,
        icon: `${prefix}-font-size-icon`,

        heading: {
            h1: `${prefix}-font-size-h1`,
            h2: `${prefix}-font-size-h2`,
            h3: `${prefix}-font-size-h3`,
            h4: `${prefix}-font-size-h4`,
            h5: `${prefix}-font-size-h5`,
        },
    },
    lineHeight: {
        default: `${prefix}-line-height`,
        lg: `${prefix}-line-height-lg`,
        sm: `${prefix}-line-height-sm`,

        heading: {
            h1: `${prefix}-line-height-heading-h1`,
            h2: `${prefix}-line-height-heading-h2`,
            h3: `${prefix}-line-height-heading-h3`,
            h4: `${prefix}-line-height-heading-h4`,
            h5: `${prefix}-line-height-heading-h5`,
        },
    },
    fontHeight: {
        default: `${prefix}-font-height`,
        lg: `${prefix}-font-height-lg`,
        sm: `${prefix}-font-height-sm`,
    },
    opacityLoading: `${prefix}-opacity-loading`,
    boxShadow: {
        default: `${prefix}-box-shadow`,
        secondary: `${prefix}-box-shadow-secondary`,
        tertiary: `${prefix}-box-shadow-tertiary`,
    },
})
